Full code cleanup/refactor. quBSD library.

diff --git a/zroot/usr/local/bin/qb-connect b/zroot/usr/local/bin/qb-connect
--- a/zroot/usr/local/bin/qb-connect
+++ b/zroot/usr/local/bin/qb-connect
@@ -1,327 +1,215 @@
 #!/bin/sh
 
-while getopts dhi:ls o ; do
-	case $o in
-		d) destroy="true" ;;
-		h) help="true" ;;
-		i) IP0="$OPTARG" manualIP="true" ;;
-		l) list="true" ;; 
-	esac
-done
+. /usr/local/lib/quBSD/quBSD.sh
+. /usr/local/lib/quBSD/msg-connect.sh
 
-shift $(( OPTIND - 1 ))
-
-QBCONF="/usr/local/etc/quBSD/quBSD.conf"
-JMAP="/usr/local/etc/quBSD/jailmap.conf"
-
-# Get datasets, mountpoints; and define files.
-zusr_zfs=$(sed -En "s/^zusr_dataset[[:blank:]]+//p" $QBCONF)
-m_zusr=$(zfs get -H mountpoint $zusr_zfs | awk '{print $3}')
-jails_zfs=$(sed -En "s/^jails_dataset[[:blank:]]+//p" $QBCONF)
-m_jails=$(zfs get -H mountpoint $jails_zfs | awk '{print $3}')
-
-mtu=$(sed -nE "s:^mtu[[:blank:]]+::p" $QBCONF)
-
-# Define script variables
-jail=${jail:="$1"}
-tunnel="$2"
-
-define_variables() {
-	onjails=$(jls | awk '{print $2}' | tail -n +2)
-	for j in $onjails ; do 
-		# Assemble a list of all interfaces for all running jails
-		interfaces=$(jexec -l -U root $j ifconfig -l | sed "s/lo0//" \
-					| sed -E "s/bridge[^[:blank:]]+//g")
-
-		for i in $interfaces ; do
-			intf_IP=$(jexec -l -U root $j ifconfig -f inet:cidr $i inet \
-				| egrep -o "inet [^[:blank:]]+" | sed "s/inet //") 
-			all_interfaces=$(printf "%b" "$all_interfaces\n$j $i $intf_IP")
-		done
-
-		# For readibility, bridges and their members are listed last for each jail
-		bridges=$(jexec -l -U root $j ifconfig -l | egrep -o "bridge[^[:blank:]]+")
-		for b in $bridges ; do
-			bridge_IP=$(jexec -l -U root $j ifconfig -f inet:cidr $b inet \
-					| egrep -o "$b|inet [^[:blank:]]+" | sed "s/inet //") 
-			all_interfaces=$(printf "%b" "$all_interfaces\n$j $bridge_IP")
-
-			members=$(jexec -l -U root $j ifconfig $b | egrep -o "member: [^[:blank:]]+" \
-					| sed -E "s/member/$j $b member/g" | sed "s/:[[:blank:]]*/:/g")
-			all_interfaces=$(printf "%b" "$all_interfaces\n$members")
-		done
+get_options() {
+	while getopts cdhi:l opts ; do
+		case $opts in
+			c) _CMD="create" ;;
+			d) [ -z "$_CMD" ] && _CMD="destroy" || get_msg_qb_connect "_1" "usage_1" ;;
+			h) get_msg_qb_connect "none" "usage_0" ;;
+			i) IP0="$OPTARG" manualIP="true" ;;
+			l) [ -z "$_CMD" ] && _CMD="list" || get_msg_qb_connect "_1" "usage_1" ;;
+		esac
 	done
 
-	# Clean up and categorize all_interfaces list for later usage
-	all_interfaces=$(echo "$all_interfaces" | column -t)
-	jail_interfaces=$(echo "$all_interfaces" | egrep "^$jail ") 
-	jailepairs=$(echo "$jail_interfaces" | awk '{print $2}' | egrep -o "epair[[:digit:]]+")	
-	tunnel_pairs=$(echo "$all_interfaces" | egrep -v "^$jail" | egrep "$jailepairs")	
+	shift $(( OPTIND - 1 ))
 
-	# Get JMAP IP assignments to prevent overlap if auto-assiging a new epair IP
-	JMAPIPs=$(qb-list -p IP0 | sort -k3)
-
-	# Seclvl of 3 would prevent modifying pf. Warning will be issued if so 
-	if [ "$tunnel" ] ; then
-		if `jls | grep -qs " $tunnel "` ; then
-			tunnel_seclvl=$(jexec -l -U root $tunnel sysctl kern.securelevel \
-										| sed "s/kern.securelevel: //")
-		else 
-			tunnel_seclvl=$(sed -nE "s/^${tunnel}[[:blank:]]+seclvl[[:blank:]]+//p" $JMAP)
-		fi
-	fi
-
-	if [ "$jail" ] ; then 
-		if `jls | grep -qs " $jail"` ; then
-			jail_seclvl=$(jexec -l -U root $jail sysctl kern.securelevel \
-										| sed "s/kern.securelevel: //")
-		else 
-			jail_seclvl=$(sed -nE "s/^${jail}[[:blank:]]+seclvl[[:blank:]]+//p" $JMAP)
-		fi
-	fi
-}
-
-define_messages() {
-	err1="qb-connect: ERROR: Jail:  $jail doesn't exist or is not turned on" 
-	err1_1="qb-connect: ERROR:  $tunnel doesn't exist or isn't fully configured" 
-	err2="qb-connect: ERROR: Must specify target jail or [-l] option"
-	err3="qb-connect: ERROR: Must specify a tunnel-jail to connect to"
-	err4="qb-connect: ERROR: Tunnel jail:  $tunnel is not turned on" 
-	err5="qb-connect: ERROR: [-i $IP0] is not a valid CIDR IPv4 address" 
-	err6="qb-connect: ERROR: User opted to exit, to change [-i] specification" 
-	warn7=$(printf "%b" "\nWARNING: [-i] overlaps with an IP already in use.\n" \
-					"Continue with $IP0 anyways? (y/n): ")
-	warn8=$(printf "%b" "\nWARNING:  $jail has kern.securelevel=3 applied, and there is" \
-					"\na pf.conf in the the jail's config. It's likely that the pf config" \
-					"\nwill force all packets to be dropped between $jail and $tunnel" \
-					"\nContinue anyways? (y/n): ")
-	err8=$(printf "%b" "qb-connect: ERROR: User opted to exit. Recommend changing the" \
-					"\nseclvl to 2 or less, restart the jail(s), and re-run qb-connect.")
-	warn9=$(printf "%b" "\nWARNING:  $tunnel has kern.securelevel=3 applied, and there is" \
-					"\na pf.conf in the the jail's config. It's likely that the pf config" \
-					"\nwill force all packets to be dropped between $jail and $tunnel" \
-					"\nContinue anyways? (y/n): ")
-	err9=$(printf "%b" "qb-connect: ERROR: Couldn't find an IP address available within" \
-					"\nthe quBSb internal IP conventions for this jail-tunnel pair." \
-					"\nNormally IP is between:  $ip0_0  and  $ip0" \
-					"\nRecommend running again with [-i <IPv4>] manually assigned.")
-	err10=$(printf "%b" "qb-connect: ERROR:  $jail start exited with errors.") 
-	msg11=$(printf "%b" "qb-connect: ALERT:  $jail and $tunnel are connected, but pfctl," \
-					"\ndefault route, and /etc/resolv.conf have not been configured.")
-	msg12=$(printf "%b" "qb-connect: ALERT:  When connecting net-<jail> to net-tap, you likely" \
-					"\nneed to manual modify pf.conf in $jail for connection to funciton")
-}
-
-usage() {
-	[ -n "$ERR" ] && printf "%b" "\n$ERR\n"
-	echo ""
-	echo "qb-connect:  Create / list virtual interfaces between two jails"
-	echo "IP is auto assigned, but can be manually specified. Additionally"
-	echo "pfctl, resolve.conf, and default route are autoconfigured"
-	echo ""
-	echo "Usage: qb-connect [-i <IPv4>] <target-jail> <tunnel-jail>" 
-	echo "       qb-connect [-d][-l] <target-jail>"
-	echo "       qb-connect -d <target-jail> <tunnel-jail>"
-	echo ""
-	echo "   -d: (d)estroy all epairs for the target. If tunnel jail is specified"
-	echo "        then only epairs common to the target/tunnel pair are destroyed"
-	echo "   -h: (h)elp:  Outputs this help message"
-	echo "   -i: (i)p:  Override auto IP assignment. Must be valid IPv4 in CIDR"
-	echo "        notation.  Include the subnet:  IP.IP.IP.IP/subnet"
-	echo "   -l: (l)ist:  All interfaces and IPs for all running jails. If" 
-	echo "        <jail> is specified, list outputs interfaces only for <jail>" 
-	echo ""
-	exit 1
+	# Define script variables
+	JAIL=${JAIL:="$1"}
+	TUNNEL="$2"
+	MTU=$(sed -nE "s:^mtu[[:blank:]]+::p" $QBCONF)
+	ACTION="get_msg_qubsd"
 }
 
 checks() {
-	if [ "$help" ] ; then
-		usage
+	# Must specify a _CMD 
+	[ -z "$_CMD" ] && get_msg_qb_connect "_0" "usage_1"	
 
-	elif ! `jls | grep -qs " $jail "` ; then
-		ERR="$err1" ; usage
-
-	elif [ "$tunnel" ] && ! `qb-list -qj $tunnel` ; then
-		ERR="$err1_1" ; usage
-
-	# Checks accomplished for normal ops (connecting a jail/tunnel)
-	elif [ -z "$list" -a -z "$destroy" ] ; then
-		if [ -z "$jail" ] ; then
-			ERR="$err2" ; usage
-
-		elif [ -z "$tunnel" ] ; then
-			ERR="$err3" ; usage
-
-		# Standard checks for a manually specified IP
-		elif [ "$manualIP" ] ; then
-			if [ -z "$validIPv4" ] ; then
-				ERR="$err5" ; usage
-
-			elif `printf "%b" "$all_interfaces\n$JMAPIPs" | egrep -qs "$b3"` ; then 
-				printf "%b" "$warn7" ; read resp
-				[ "$resp" != "y" -a "$resp" != "Y" ] && ERR="$err6" && usage
-			fi
-
-		elif [ "$jail_seclvl" = 3 -a -e "${m_zusr}/$jail/rw/etc/pf.conf" ] ; then
-			printf "%b" "$warn8" ; read resp
-			[ "$resp" != "y" -a "$resp" != "Y" ] && ERR="$err8" && usage
+	case "$_CMD" in
+		create) 
+			# JAIL must be running, but tunnel can be started later 
+			check_isrunning_jail "$JAIL" "return 1" || get_msg_qb_connect "_2" "usage_1"
 			
-		elif [ "$tunnel_seclvl" = 3 -a -e "${m_zusr}/$tunnel/rw/etc/pf.conf" ] ; then
-			printf "%b" "$warn9" ; read resp
-			[ "$resp" != "y" -a "$resp" != "Y" ] && ERR="$err8" && usage
-		fi
+			# IP checks
+			if [ -n "$IP0" ] ; then
+				# Invalid IP must be rejected
+				check_isvalid_ipv4 "$IP0" "$ACTION" || exit 1 
 
-	elif [ "$destroy" ] ; then
-		if [ "$tunnel" ] && ! `jls | grep -qs " $tunnel"` ; then
-			ERR="$err4" ; usage
-		fi
-	fi
-}
-
-check_IPv4() {
-	# Perhpas not as technically correct as doing a regex,
-	# but it's readable, and the a/b pairs are usable elsewhere
-	# IPv4 cidr:  a0.a1.a2.a3/a4
-
-	validIPv4=""
-
-	a0=${IP0%%.*.*.*/*}
-	a4=${IP0##*.*.*.*/}
-		b1=${IP0#*.*}
-		a1=${b1%%.*.*/*}
-			b2=${IP0#*.*.*}
-			a2=${b2%%.*/*}
-				b3=${IP0%/*}
-				a3=${b3##*.*.*.}
-
-	if    [ "$a0" -ge 0 -a "$a0" -le 255 -a "$a1" -ge 0 -a "$a1" -le 255 \
-		-a "$a2" -ge 0 -a "$a2" -le 255 -a "$a3" -ge 0 -a "$a3" -le 255 \
-		-a "$a4" -ge 0 -a "$a4" -le 31 ] >> /dev/null 2>&1
-	then
-		echo "$IP0" | egrep -qs "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/[[:digit:]]+"
-		[ "$?" = "0" ] && validIPv4="true"
-	fi
-}
-
-find_IP() {
-	cycle=1
-	
-	# Auto IP is given form: 10.99.x.1/30 so that it's readily identifiable as temporary 
-	while [ $cycle -lt 255 ] ; do
-		# multiple if/thens to construct the IP and loop search
-		openip="10.99.${cycle}.2"
-
-		# If the IP on this cycle is not found anywhere, then it can be used
-		if ! `printf "%b" "${all_interfaces}\n${JMAPIPs}" | grep -qs "$openip"` ; then
-			IP0=${IP0:-"${openip}/30"}
-			break
-		else
-			cycle=$(( cycle + 1 ))
-			if [ $cycle -gt 254 ] ; then
-				ERR="$err9" ; usage
-			fi
-		fi
-	done
-}
-
-list_output() {
-	if [ "$list" ] ; then 
-		if [ -n "$jail" ] ; then 
-			printf "%b" "\nHere are the interfaces for:  $jail" "\n$jail_interfaces\n"
-			printf "%b" "\n$jail is connected to these jails:  "
-			if [ -n "$jailepairs" ] ; then
-				printf "%b" "\n$tunnel_pairs\n\n"
+				# Just temporary connections. Warn for convention mismatch, but don't exit  
+				check_isqubsd_ipv4 "$IP0" "$ACTION" 
 			else
-				printf "%b" "\n\n"
-			fi  
-		else
-			printf "%b" "\nAll interfaces and IP addresses for all running jails\n" \
-					"$all_interfaces\n\n"
-		fi
 
-		# Exit if use didn't specify [-d]
-		[ -z "$destroy" ] && exit 0
+				# Assign IP if not specified by user 
+				IP0=$(discover_open_ipv4 "$JAIL" "$ACTION") || exit 1 
+			fi
+			
+			# Check the pf status and security levels
+		   check_seclvl || get_msg_qb_connect "_4" "exit_1"
+		;;
+		destroy)
+			# JAIL and TUNNEL must be running (helps prevent accidents) 
+			check_isrunning_jail "$JAIL" "return 1" || get_msg_qb_connect "_2" "usage_1"
+	
+			[ -n "$TUNNEL" ] && ! check_isrunning_jail "$TUNNEL" "$ACTION" \
+					&& get_msg_qb_connect "_3" "usage_1"
+		;;
+	esac
+}
+
+check_seclvl() {
+	# If JAIL has running pf, seclvl=3 could prevent modification 
+	jexec -l -U root $JAIL service -e | grep -q "rc.d/pf" \
+			&& _seclvl_J=$(jexec -l -U root $JAIL sysctl kern.securelevel \
+					| sed "s/kern.securelevel: //")
+
+	# Return 1 to checks() if either seclvl is too high to modify network
+	[ "$_seclvl_J" == "3" ] && return 1 
+
+	# If TUNNEL has running pf, seclvl=3 could prevent modification 
+	if check_isrunning_jail "$TUNNEL" ; then
+		jexec -l -U root $TUNNEL service -e | grep -q "rc.d/pf" \
+				&& _seclvl_T=$(jexec -l -U root $TUNNEL sysctl kern.securelevel \
+																| sed "s/kern.securelevel: //") 
+	else
+		# If TUNNEL is off, but has pf_enabled, use jailmap.conf for the warning 
+		grep -Eq 'pf_enable=.*YES' ${M_ZUSR}/${TUNNEL}/rw/etc/rc.conf \
+				&& _seclvl_T=$(sed -nE "s/^${TUNNEL}[[:blank:]]+seclvl[[:blank:]]+//p" $JMAP)
+	fi
+	
+	# Return 1 if tunnel seclvl is too high. Must use if/then here, for return 0/1 to work  
+	if [ "$_seclvl_T" == "3" ] ; then 
+		return 1 
 	fi
 }
 
-destroy_epairs() {
-	if [ "$destroy" ] ; then
-		if [ -z "$tunnel" ] ; then
-			dest_epairs=$(jexec -l -U root $jail ifconfig -g epair)
+get_local_ip() {
 
-		elif [ "$destroy" -a "$tunnel" ] ; then 
-			dest_epairs=$(echo "$tunnel_pairs" | egrep "^${tunnel}[[:blank:]]+epair" \
-														| awk '{print $2}')
-		fi
+	# Finds the CIDR notated IP address of an jails interface; or `none'
+	jexec -l -U root $_jail ifconfig -f inet:cidr $_intf inet \
+		| grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/[[:digit:]]+" \
+			|| echo "none"
+}
 
-		echo "${dest_epairs%?}b" | xargs -I@ ifconfig @ -vnet $jail
-		echo "${dest_epairs%?}b" | xargs -I@ ifconfig @ destroy 
-		exit 0
-	fi
+get_bridge_members() {
+	# If _intf is a bridge, add the members
+	jexec -l -U root $_jail ifconfig $_intf | egrep -o "member: [^[:blank:]]+" \
+		| sed -E "s/member/$_jail $_intf member/g" | sed "s/:[[:blank:]]*/:/g"
+}
+
+assemble_interface_list() {
+	# For each jail that is running 
+	for _jail in $(get_onjails) ; do 
+	
+		# Cycle through every interface on that jail
+		for _intf in $(jexec -l -U root $_jail ifconfig -l) ; do	
+
+			# Pair each _jail/_intf , with the associated ip address 
+			_ALL_INTF=$(printf "%b" "$_ALL_INTF\n $_jail  $_intf  $(get_local_ip)")
+
+			# If the _intf is a bridge, add its bridge members to the list 
+			[ -z "${_intf##bridge*}" ] \
+				&& _ALL_INTF=$(printf "%b" "$_ALL_INTF\n$(get_bridge_members)")
+				
+		done
+	done
+	
+	# Remove loopbacks; and set columns formatting 
+	_ALL_INTF=$(echo "$_ALL_INTF" | grep -v "[[:blank:]]lo0[[:blank:]]" | column -t)
+
+	# Clean up and categorize all_interfaces list for later usage
+	_jail_intfs=$(echo "$_ALL_INTF" | egrep "^$JAIL ") 
+	_jail_eps=$(echo "$_jail_intfs" | awk '{print $2}' | egrep -o "epair[[:digit:]]+")	
+	_tunnel_pairs=$(echo "$_ALL_INTF" | egrep -v "^$JAIL" | egrep "$_jail_eps")	
 }
 
 configure_epairs() {
 	# Start tunnel if it's off
-	if ! `jls | grep -qs " $tunnel "` ; then
-		read -p "$tunnel is off.  Start it? y/n: " p
-		if [ "$p" = "y" ] ; then
-			jail -c $tunnel >> /dev/null
-			[ "$?" != "0" ] && ERR="$err10" && usage
-		else
-			exit 0
-		fi
-	fi
+	check_isrunning_jail "$TUNNEL" || start_jail "$TUNNEL" "$ACTION" || exit 1
 
 	# Create the epair and send to jails
-     epair=$(ifconfig epair create)
-     ifconfig "${epair%?}a" vnet $tunnel
-     ifconfig "${epair%?}b" vnet $jail
+	epair=$(ifconfig epair create)
+	ifconfig "${epair%?}a" vnet $TUNNEL
+	ifconfig "${epair%?}b" vnet $JAIL
 
-     # If tunnel contains a tap interface, connect epair to bridge
-     if [ -z "${tunnel##net-tap*}" ] ; then
-          jexec -l -U root $tunnel ifconfig bridge0 addm "${epair%?}a"
-          jexec -l -U root $tunnel ifconfig "${epair%?}a" up
-		printf "%b" "\n$msg12\n"
+	# Apply IP0 to JAIL and TUNNEL
+	jexec -l -U root $JAIL ifconfig "${epair%?}b" inet $IP0 mtu $MTU up
 
-	elif [ "$IP0" -a "$tunnel" ] ; then
-		# Apply IP0 to tunnel		
-          jexec -l -U root $tunnel ifconfig "${epair%?}a" \
-						inet "${IP0%.*/*}.1/${IP0#*/}" mtu $mtu up
-	fi	
-
-	if [ "$IP0" ] ; then
-		# Apply IP0 to jail
-	     jexec -l -U root $jail ifconfig "${epair%?}b" inet $IP0 mtu $mtu up
-	fi
+	jexec -l -U root $TUNNEL ifconfig "${epair%?}a" \
+										inet "${IP0%.*/*}.1/${IP0#*/}" mtu $MTU up
 }
 
 configure_network() {
 	# Add the IP to the tunnel's pf table
-	if [ -e "${m_jails}/${tunnel}/rw/etc/pf.conf" -a "$tunnel_seclvl" -lt 3 ] ; then
-		jexec -l -U root $tunnel pfctl -t pass_ips -T add $IP0
-	fi
+	[ -e "${M_JAILS}/${TUNNEL}/rw/etc/pf.conf" ] \
+			&& jexec -l -U root $TUNNEL pfctl -t pass_ips -T add $IP0
 
 	# Add the IP to the jail's pf table
-	if [ -e "${m_jails}/${jail}/rw/etc/pf.conf" -a "$jail_seclvl" -lt 3 ] ; then
-		jexec -l -U root $jail pfctl -t pass_ips -T add $IP0
-	fi
+	[ -e "${M_JAILS}/${JAIL}/rw/etc/pf.conf" ] \
+			&& jexec -l -U root $JAIL pfctl -t pass_ips -T add $IP0
 
 	# Add default route and a resolv.conf for jail to connect to the internet
-	jexec -l -U root $jail route add default "${IP0%.*/*}.1"
-	cp ${m_zusr}/${tunnel}/rw/etc/resolv.conf ${m_jails}/${jail}/rw/etc/
-
-	echo ""
+	jexec -l -U root $JAIL route add default "${IP0%.*/*}.1"
+	cp ${M_ZUSR}/${TUNNEL}/rw/etc/resolv.conf ${M_JAILS}/${JAIL}/rw/etc/
 }
 
+destroy_epairs() {
+	if [ -z "$TUNNEL" ] ; then
+		
+		# If no tunnel, destroy all epairs on JAIL
+		_destr_epairs=$(jexec -l -U root $JAIL ifconfig -g epair)
+	else
+		
+		# Othewise only remove the epairs common to both JAIL and TUNNEL	
+		_destr_epairs=$(echo "$_tunnel_pairs" | egrep "^${TUNNEL}[[:blank:]]+epair" \
+														| awk '{print $2}')
+	fi
 
-define_variables
-check_IPv4
-find_IP
-define_messages
+	echo "${_destr_epairs%?}b" | xargs -I@ ifconfig @ -vnet $JAIL
+	echo "${_destr_epairs%?}b" | xargs -I@ ifconfig @ destroy 
+}
+
+list_output() {
+
+	if [ -n "$JAIL" ] ; then 
+		
+		# Show the interfaces on JAIL 
+		get_msg_qb_connect "_5" 
+
+		# Show all other jails that connect to JAIL
+		[ -n "$_jail_eps" ] && get_msg_qb_connect "_6" 
+	else
+		
+		# List all existing connections for all running jails
+		get_msg_qb_connect "_7" 
+	fi
+}
+
+main() {
+	case $_CMD in 
+		create)
+				configure_epairs
+				configure_network
+		;;
+		destroy)
+				assemble_interface_list	
+				destroy_epairs
+		;;
+		list)
+				assemble_interface_list	
+				list_output
+		;;
+	esac
+}
+
+get_global_variables
+
+get_options "$@"
+
 checks
-list_output 
-destroy_epairs 
-configure_epairs
-configure_network
+
+main
+
 
 
diff --git a/zroot/usr/local/bin/qb-pefs b/zroot/usr/local/bin/qb-pefs
--- a/zroot/usr/local/bin/qb-pefs
+++ b/zroot/usr/local/bin/qb-pefs
@@ -1,118 +1,105 @@
 #!/bin/sh
 
-while getopts chd:u o ; do
-	case $o in
-		c) create="true" ;;
-		h) help="true" ;;
-		d) directory="$OPTARG" ;;
-		u) unmount="true" ;;
-	esac
-done
+# pefs is tricky when dealing with the nullfs mounts of jails from zusr to zroot
+# addkey only affects the mount directory *even if it's nullfs mounted elsewhere*
+# In other words, the pefs addchain/remove chain will not follow the nullfs mount
+# For this reason, nullfs must be applied again, after pefs addkey, and later removed in order
 
-shift $(( OPTIND - 1 ))
+. /usr/local/lib/quBSD/quBSD.sh
+. /usr/local/lib/quBSD/msg-pefs.sh
 
-QBCONF="/usr/local/etc/quBSD/quBSD.conf"
+get_options() {
+	while getopts chd:mu opts ; do
+		case $opts in
+			c) _CMD="create" ;; 
+			h) get_msg_qb_pefs "none" "usage_0" ;; 
+			d) U_FOLDER="$OPTARG" USERDIR="true" ;;
+			m) [ -z "$_CMD" ] && _CMD="mount" || get_msg_qb_pefs "_1" "usage_1" ;; 
+			u) [ -z "$_CMD" ] && _CMD="unmount" || get_msg_qb_pefs "_1" "usage_1" ;; 
+		esac
+	done
 
-# Get datasets and mountpoints
-zusr_zfs=$(sed -En "s/^zusr_dataset[[:blank:]]+//p" $QBCONF)
-m_zusr=$(zfs get -H mountpoint $zusr_zfs | awk '{print $3}')
-jails_zfs=$(sed -En "s/^jails_dataset[[:blank:]]+//p" $QBCONF)
-m_jails=$(zfs get -H mountpoint $jails_zfs | awk '{print $3}')
+	shift $(( OPTIND - 1 ))
 
-# Define script variables
-jail="$1"
+	JAIL="$1"
+	ACTION="get_msg_qubsd"
 
-define_variables() {
-	# If -z $directory, pefs_dirs will find all .pefs.db directories (for unmount)
-	rel_directory=$(echo $directory | sed "s:${m_zusr}/${jail}/usr/home/${jail}/::")
-	pefs_dirs=$(find ${m_jails}/${jail}/usr/home/${jail}/${rel_directory} -name '.pefs.db' \
-														| sed 's:/.pefs.db::g')
 	# Default directory if not defined by user
-	directory="${directory:-$2}" 
-	directory="${directory:-${m_zusr}/${jail}/usr/home/${jail}/crypt}"
-
-	# Must find rel_directory again for ops not related to unmount
-	rel_directory=$(echo $directory | sed "s:${m_zusr}/${jail}/usr/home/${jail}/::")
-}
-
-define_messages() {
-	err1=$(printf "%b" "qb-pefs: ERROR: You must enter a jailname")
-	err2=$(printf "%b" "qb-pefs: ERROR: $j is an invalid jailname or has incomplete jail setup")
-	err3=$(printf "%b" "qb-pefs ERROR: $directory not a valid" \
-					"\ndirectory, and user has not specified the [-c] option to create it")
-	err5=$(printf "%b" "qb-pefs ERROR: Failed to load pefs.ko kernel module." \
-					"Make sure that pefs-kmod pkg in installed to host")
-	msg6=$(printf "%b" "Jail must be on, starting: $jail")
-	err7=$(printf "%b" "Start jail: $jail , failed, exiting") 
-	msg8=$(printf "%b" "Decrypting container, enter passphrase one more time:")
-}
-
-usage() {
-	[ "$ERR" ] && printf "%b" "\n$ERR\n"
-	echo ""
-	echo "qb-pefs: Mounts an encrypted pefs volume inside of a running jail" 
-	echo "         Default directory is ${m_zusr}/<jail>/usr/home/<jail>/crypt"
-	echo ""
-	echo "Usage: qb-pefs <jailname>"
-	echo "Usage: qb-pefs [-h] [-d <directory>] <jailname>"
-	echo "   -c: (c)reate:  Create and configure new pefs directory" 
-	echo "   -d: (d)irectory:  Override default, and mount specified directory" 
-	echo "        <directory> must be entered based on location of HOST "
-	echo "        <directory> must be inside zusr home directory of jail"
-	echo "   -h: (h)elp:  Outputs this help message"
-	echo "   -u: (u)nmount:  Removes pefs mount from jail, encrypts files" 
-	echo ""
-	exit 1
+	U_FOLDER="${U_FOLDER:=${M_ZUSR}/${JAIL}/usr/home/${JAIL}/crypt}"
 }
 
 checks() {
-	if [ "$help" ] ; then
-		usage
+	# Must specify an action
+	[ -z "$_CMD" ] && get_msg_qb_pefs "_2" "usage_1"
 
-	elif [ -z "$jail" ] ; then
-		ERR="$err1" ; usage
+	# Must have a valid jail 
+	check_isvalid_jail "$JAIL" "$ACTION" || get_msg_qb_pefs "none" "usage_1"
 
-	elif ! `qb-list -qj "$jail"` ; then
-		ERR="$err2" ; usage
+	# If performing mount, the directory should already exist. 
+	[ "$_CMD" == "mount" ] && ! [ -d "$U_FOLDER" ] && get_msg_qb_pefs "_3" "usage_1"
 
-	elif ! [ -d "$directory" -o -n "$create" ] ; then
-		ERR="$err3" ; usage
-
-	elif ! `kldstat | grep -qs "pefs.ko"` ; then
-		kldload pefs.ko >> /dev/null 2>&1
-		if [ "$?" != "0" ] ; then
-			ERR="$err5" ; usage
-		fi
-	fi
+	# Check that U_FOLDER path is relative to the zusr mount for the jail
+	echo "$U_FOLDER" | grep -qE "^${M_ZUSR}/${JAIL}" || get_msg_qb_pefs "_4" "usage_1"
+				
+	# Make sure pefs kernel module is loaded, try to load, or exit on failure
+	kldstat -n pefs.ko > /dev/null 2>&1 || kldload pefs.ko > /dev/null 2>&1 \
+			|| get_msg_qb_pefs "_5" "exit_1"
 }
 
 main() {
-	if [ "$unmount" ] ; then
-		for p in $pefs_dirs ; do
-			umount -f $p
-		done
-		exit 0
-
-	elif ! `jls | grep -qs " $jail "` ; then
-		printf "%b" "\n$msg6\n"
-		jail -c $jail >> /dev/null 2>&1
-		[ "$?" != "0" ] && ERR="$err7" && usage
-	fi
+	# Mount also takes place in running jail. Replace zusr mount with zroot jails mount 
+	J_FOLDER=$(echo $U_FOLDER | sed "s:${M_ZUSR}:${M_JAILS}:")	
 	
-	if [ "$create" ] ; then
-		mkdir -p $directory
-		chown 1001:1001 $directory
-		pefs addchain -fZ $directory
-	fi
+	case $_CMD in 
 
-	pefs mount $directory ${m_jails}/${jail}/usr/home/${jail}/${rel_directory}
-	[ "$create" ] && printf "%b" "\n$msg8\n"
-	pefs addkey -c ${m_jails}/${jail}/usr/home/${jail}/${rel_directory}
+		create)
+			mkdir -p $U_FOLDER > /dev/null 2>&1
+			pefs addchain -fZ $U_FOLDER
+			chown 1001:1001 $U_FOLDER
+		;;
+
+		mount)
+			# Start jail if off, or exit
+			start_jail "$JAIL" "$ACTION" || exit 1
+
+			# Mount the folder and perform decryption
+			pefs mount $U_FOLDER $U_FOLDER
+			pefs addkey -c $U_FOLDER
+
+			# Must send the nullfs mount over to the jail, so inside jail can see files
+			mount_nullfs $U_FOLDER $J_FOLDER
+		;;
+
+		unmount)	
+			# If user specified directory, then unmount only that directory 
+			if [ -n "$USERDIR" ] ; then 
+
+				# The unmount must be done in reverse order. First the nullfs to the zroot/jail
+				umount -f $J_FOLDER
+				# Then the original pefs mount, which encrypts the files
+				umount -f $U_FOLDER
+			else
+
+				# Otherwise, search <jail>'s /usr/local for all pefs.db, to remove 
+				_zusr_umnt=$(find ${M_ZUSR}/${JAIL}/usr -name '.pefs.db' \
+						| sed 's:/.pefs.db::g')  
+
+				# Unmount directories  
+				for _dir in $_zusr_umnt ; do
+					umount -f $(echo $_dir | sed "s:${M_ZUSR}:${M_JAILS}:")	
+					umount -f $_dir 
+				done
+			fi
+		;;
+
+	esac
 }
 
-define_variables
-define_messages
-checks
-main
+get_global_variables
 
+get_options "$@"
+
+checks
+
+main
 
diff --git a/zroot/usr/local/bin/qb-snap b/zroot/usr/local/bin/qb-snap
--- a/zroot/usr/local/bin/qb-snap
+++ b/zroot/usr/local/bin/qb-snap
@@ -1,179 +1,130 @@
 #!/bin/sh
 
-while getopts dhln o ; do
-	case $o in
-		d) dest_oldest="true" ;;
-		h) help="true" ;;
-		l) list_all="true" ;;
-		n) new="true" ;;
-	esac
-done
+. /usr/local/lib/quBSD/quBSD.sh
+. /usr/local/lib/quBSD/msg-snap.sh
 
-shift $(( OPTIND - 1 ))
+get_options() {
+	while getopts cd:hly opts ; do
+		case $opts in
+			c) _CMD="create" ;;
+			d) [ -z "$_CMD" ] && _CMD="destroy" || get_msg_qb_snap "_1" "exit_1" 
+				DEL_DATE="$OPTARG" ;;
+			h) get_msg_qb_snap "none" "usage_0" ;; 
+			l) [ -z "$_CMD" ] && _CMD="list"  || get_msg_qb_snap "_1" "exit_1" ;;
+			y) assume_yes="true" ;;
+		esac
+	done
 
-QBCONF="/usr/local/etc/quBSD/quBSD.conf"
-JMAP="/usr/local/etc/quBSD/jailmap.conf"
+	shift $(( OPTIND - 1 ))
 
-# Get datasets, mountpoints; and define files.
-zusr_zfs=$(sed -En "s/^zusr_dataset[[:blank:]]+//p" $QBCONF) 
-jails_zfs=$(sed -En "s/^jails_dataset[[:blank:]]+//p" $QBCONF) 
-
-# Define script variables
-jail="$1"
-date=$(date +%b%d)
-tyme=$(date +%H%M)
-
-define_variables() {
-	class=$(sed -nE "s/^${jail}[[:blank:]]+class[[:blank:]]+//p" $JMAP)
-
-	# Rootjail vs zusr jails have different zfs datasets to handle 
-	if [ "$class" = "rootjail" ] ; then
-		newsnap="${jails_zfs}/${jail}@${date}_${tyme}" 
-		newdeps=$(zfs list -o name,origin | grep "${newsnap}" | awk '{print $1}')
-
-		# Destroy option. zfs lists snapshots in chronological order 
-		if [ "$dest_oldest" ] ; then
-			oldsnap=$(zfs list -t snapshot | awk '{print $1}' \
-								| grep "${jails_zfs}/${jail}@" | head -1)
-			olddeps=$(zfs list -o name,origin | grep "${oldsnap}" | awk '{print $1}') 
-		fi
-	else
-		newsnap="${zusr_zfs}/${jail}@${date}_${tyme}"
-		newdeps=$(zfs list -o name,origin | grep "${newsnap}" | awk '{print $1}')
-
-		if [ "$dest_oldest" ] ; then 
-			oldsnap=$(zfs list -t snapshot | awk '{print $1}' \
-								| grep "${zusr_zfs}/${jail}@" | head -1)
-			olddeps=$(zfs list -o name,origin | grep "${oldsnap}" | awk '{print $1}') 
-		fi
-	fi
-	`zfs list -t snapshot | grep -qs $newsnap` && dupl="true"
-}
-
-define_messages() {
-	err1=$(printf "%b" "qb-snap: ERROR: need to specify an action [-d|-l|-n]")
-	err2=$(printf "%b" "qb-snap: ERROR: Need to list jail")
-	err2_1=$(printf "%b" "qb-snap: ERROR: $jail doesn't exist or isn't configured properly")
-	warn3=$(printf "%b" "qb-snap: WARNING: Snapshot with name, $newsnap, already exists." \
-					"\nReplace?(y/n):  ")
-	warn4=$(printf "%b" "qb-snap: The oldest snapshot: $oldsnap has the following dependencies:")
-	warn5=$(printf "%b" "These jails will be shutdown")
-	warn6=$(printf "%b" "Data inside these jails will be permanently destroyed")
-	warn7=$(printf "%b" "qb-snap: WARNING:  "$newsnap" has the following dependencies:")
-}
-
-usage() {
-	[ "$ERR" ] && printf "%b" "\n$ERR"
-	echo ""
-	echo "qb-snap: Quickly create/view snapshot datasets for <jail>" 
-	echo "Snapshot names default to the form of:  jail@MonDD_HHMM"
-	echo ""
-	echo "Usage: qb-snap [-d|-l|-n] <jail>" 
-	echo "   -d: (d)estroy oldest snapshot of <jail>"
-	echo "   -h: (h)elp . Outputs this help message"
-	echo "   -l: (l)ist all snapshots of <jail>."
-	echo "        If no argument is provided, lists all snapshots"
-	echo "   -n: (n)ew snapshot for <jail>"
-	echo ""
-	exit 1
+	# Define script variables
+	JAIL="$1"
+	ACTION="get_msg_qubsd"
 }
 
 checks() {
-	if [ "$help" ] ; then
-		usage
+	# Must specify a _CMD to execute 
+	[ -z "$_CMD" ] && get_msg_qb_snap "_2" "usage_1"
 
-	elif ! [ "$dest_oldest" -o "$list_all" -o "$new" ] ; then
-		ERR="$err1" ; usage
+	# Must have a valid jail
+	check_isvalid_jail "$JAIL" "$ACTION" || "usage_1"
 
-	elif [ -z "$list_all" -a -z "$jail" ] ; then 
-		ERR="$err2" ; usage
+	# Define _ZJAIL variable, which sets the zfs dataset being targeted 
+		# Class will determine what the target dataset is 
+		CLASS=$(sed -nE "s/^${JAIL}[[:blank:]]+class[[:blank:]]+//p" $JMAP)
+	
+		# var $_ZFS prevents multiple if/then statements later on.
+		[ "$CLASS" == "rootjail" ] && _ZFS="${JAILS_ZFS}" || _ZFS="${ZUSR_ZFS}"
 
-	elif [ "$jail" ] && ! `qb-list -qj "$jail"` ; then 
-		ERR="$err2_1" ; usage
+	# _CMD specific checks and variable assignments
+	case $_CMD in 
+		create)
+			# Standard snapshot label for [-c] create 
+			DATELABEL=$(date +@%b%d_%H:%M_USER)
 
-	elif [ "$new" -a "$dupl" ] ; then
-		printf "%b" "\n$warn3"
-		read resp
-		[ "$resp" = "y" -o "$r" = "Y" ] && replace="true" || exit 0 
-	fi
-
-	if [ "$oldsnap" -a "$olddeps" ] ; then
-		printf "%b" "\n${warn4}\n${olddeps}\n\n" 
-
-		if [ "$root" ] ; then
-			printf "%b" "\n${warn5}"
-		else
-			printf "%b" "\n${warn6}\n"
-		fi
-
-		read -p "Continue (y/n) :" resp
-		[ "$resp" = "y" -o "$r" = "Y" ] && : || exit 0 
-	fi
-
-	if [ "$replace" -a "$dupl" -a "$newdeps" ] ; then
-		printf "%b" "\n$warn7\n$newdeps\n" 
-		
-		if [ "$root" ] ; then
-			printf "%b" "\n${warn5}"
-		else
-			printf "%b" "\n${warn6}"
-		fi
-
-		read -p "Continue (y/n) :" r
-		[ "$r" = "y" -o "$r" = "Y" ] && : || exit 0 
-	fi
+			# Check for duplicate snapshot under same name. Suppress output
+			zfs list ${_ZFS}/${JAIL}${DATELABEL} > /dev/null 2>&1 && get_msg_qb_snap "_4" "exit_1"
+		;;
+		destroy)
+			# Translate user date input, to epoch. Exit if failure.
+			_del_epoch=$(date -j -f "%Y-%m-%dT%H:%M" "$DEL_DATE" "+%s") || exit 1
+		;;
+	esac
 }
 
-list_snaps() {
-	if [ "$list_all" ] ; then
-		echo ""
+get_destroy_list() {
+	# Get list of existing snapshots for <jail>, and cycle through them
+	for _snap in $(zfs list -t snapshot -Ho name ${_ZFS}/${JAIL}) ; do
 
-		if [ -z "$jail" ] ; then
-			zfs list -t snapshot 
+		# Pull the creation date for each snap, and convert to epoch time	
+		_snap_date=$(zfs list -Ho creation $_snap)
+		_snap_epoch=$(date -j -f "%a %b %d %H:%M %Y" "$_snap_date" "+%s")
+
+		# Snapshots older than user entered date, will be destroyed 
+		if [ "$_snap_epoch" -le "$_del_epoch" ] ; then
+			
+			# Create a list of all snapshots to destroy 
+			_DESTROY=$(printf "%b" "${_DESTROY}\n${_snap}") \
+			
+			# Find jails that depend on the snapshot, and create a list of depends
+			_snap_deps=$(zfs list -rHo name,origin $_ZFS | sed -nE "\#${_snap}#s#^${_ZFS}/##p")
+			_DEPENDS=$(printf "%b" "${_DEPENDS}\n${_snap_deps}")
+
 		else
-			zfs list -t snapshot | grep "$jail@"
+			# ZFS prints chronologically. Break at first snapshot newer than <date> 
+			break
 		fi
-
-		echo ""
-		exit 0
-	fi
+	done
 }
 
 main() {
-	if [ "$dest_oldest" ] ; then
-		olddeps="${olddeps##*/)}"
-		for o in $olddeps ; do
-			`jls | grep -qs " $o "` && qb-off $o
-		done
+	# Main program execution
+	case "$_CMD" in 
+		create) 
+			# Create the new snapshot
+			echo	zfs snapshot "${_ZFS}/${JAIL}${DATELABEL}" && get_msg_qb_snap "_5" 
+		;;
+		destroy)		
+			# Assemble list of all snapshots older than user input <date>
+			get_destroy_list
 
-		`jls | grep -qs " $jail "` && qb-off $jail
-		zfs destroy -Rf $oldsnap
-	fi
+			# Exit if there were no snapshots to destroy
+			[ -z "$_DESTROY" ] && get_msg_qb_snap "_6" "exit_0"
 
-	if [ "$replace" -a "$dupl" ] ; then
-		newdeps="${newdeps##*/}"
-		for n in $newdeps ; do
-			`jls | grep -qs " $n "` && qb-off $n
-		done
-		`jls | grep -qs " $jail "` && qb-off $jail
-		zfs destroy -Rf $newsnap
-	fi
+			# Present user with destroy and dependencies lies	
+			if [ -z "$assume_yes" ] ; then
+				get_msg_qb_snap "_7" 
+				get_user_response "severe" || get_msg_qb_snap "_8" "exit_0"
+			fi
 
-	if [ "$new" ] ; then
-		zfs snapshot $newsnap 
-		printf "%b" "\nCreated new snapshot: $newsnap\n"
-	fi
+			# Stop jails dependent on snapshot
+			_DEPENDS=$(echo "$_DEPENDS" | awk '{print $1}') 
 
-	list_all="true"
-	echo "New state of $jail snapshots is:"
+			for _jail in $_DEPENDS ; do
+				stop_jail "$_jail" "$ACTION" || get_msg_qb_snap "_9" "exit_1"
+			done			
+
+			# Destroy snapshots 
+			for _dsnap in $_DESTROY ; do
+				zfs destroy $_dsnap	
+			done			
+			
+			get_msg_qb_snap "_10"
+		;;
+		list)
+			#Show amended state of snapshots for <jail> 
+			zfs list -t snapshot -o name,used,creation "${_ZFS}/${JAIL}"
+		;;
+	esac
 }
 
+get_global_variables
 
-define_variables
-define_messages
+get_options "$@"
+
 checks
-list_snaps 
+
 main
-list_snaps 
+
 
 
