Fixing double-run of trap func due to monitor_startstop

diff --git a/zroot/usr/local/bin/qb-stop b/zroot/usr/local/bin/qb-stop
--- a/zroot/usr/local/bin/qb-stop
+++ b/zroot/usr/local/bin/qb-stop
@@ -21,7 +21,7 @@ get_options() {
 	_POSPARAMS=$(printf '%s\n' "$@" | uniq)
 
 	# Trap function important for keeping the lock, timeout, and coordination files clean
-	trap "cleanup_trapped ; rm_errfiles" INT TERM HUP QUIT EXIT
+	trap "cleanup_trapped" INT TERM HUP QUIT EXIT
 
 	_TMP_LOCK="${QTMP}/.qb-startstop_lock"
 	_TMP_TIME="${QTMP}/.qb-startstop_timeout"
@@ -88,7 +88,6 @@ begin_waterfall() {
 	# SUBGATEWAYS have clients, and need to be stopped serially, and recursed.
 	# Note that this script would not support multi-pathed gateway/client relationships
 	_JAILS="$1"
-
 	for _JAIL in $_JAILS; do
 
 		# Serial stop for gateways. Exception: VMs can stop in background (no VIF race conds)
@@ -98,7 +97,6 @@ begin_waterfall() {
 		_SUBGATEWAYS='' ; _ENDPOINTS=''
 
 		for _client in $(get_info -e _CLIENTS $_JAIL); do
-
 			# If the _client has no further clients, it returns 1, and is an ENDPOINT
 			get_info _CLIENTS "$_client" \
 				&& _SUBGATEWAYS="$_SUBGATEWAYS $_client" \
@@ -107,7 +105,6 @@ begin_waterfall() {
 
 		# Stop each endpoint
 		for _end in $_ENDPOINTS ; do
-
 			# Maintain a small stagger between parallel stops. Helps prevent conflicts
 			sleep .1
 
@@ -153,6 +150,7 @@ cleanup_trapped() {
 
 	# Other TMP files should all be removed immediately
 	rm $_TMP_IP $_TMP_TIME $_TMP_SNAPS > /dev/null 2>&1
+	rm_errfiles
 }
 
 main() {
@@ -205,10 +203,19 @@ main() {
 	monitor_startstop "${_TIMEOUT:=$(( _STOPS * 10 ))}" &
 	_MONITOR_PID="$!"
 
+	# Unset trap, coz otherwise it runs 2x if monitor_startstop timeout.
+	trap "" INT TERM HUP QUIT EXIT
+
 	# Wait for stops to finish. If TIMEOUT, monitor_startstop will kill -15 this script
 	ps -p $_WF_PIDS > /dev/null 2>&1 && wait $_WF_PIDS && get_msg2 -m _m2
 
-	[ "$_RESTART" ] && cleanup_trapped && rm_errfiles && exec /usr/local/bin/qb-start "$_JLIST"
+	# monitor_startstop `kill -15` doesnt cause execution to stop, so this actually runs now
+	cleanup_trapped
+
+	# If restart, clean up the tracker files, then fork to qb-start
+	if [ "$_RESTART" ] ; then
+		exec /usr/local/bin/qb-start "$_JLIST"
+	fi
 }
 
 get_global_variables
